"""
CHANGELOG generator for CAMARA release automation.

Generates structured CHANGELOG draft sections for release-review branches.
Each release section includes API documentation links, dependency versions,
and candidate changes from merged PRs.
"""

import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pystache


TITLE_TEMPLATE = "# Changelog {repo_name}"

PREAMBLE = """\
**Please be aware that the project will have frequent updates to the main \
branch. There are no compatibility guarantees associated with code in any \
branch, including main, until it has been released. For example, changes may \
be reverted before a release is published. For the best results, use the \
latest published release.**

The below sections record the changes for each API version in each release \
as follows:

* for an alpha release, the delta with respect to the previous release
* for the first release-candidate, all changes since the last public release
* for subsequent release-candidate(s), only the delta to the previous release-candidate
* for a public release, the consolidated changes since the previous public release
"""

# Backward compatibility
HEADER_TEMPLATE = TITLE_TEMPLATE + "\n\n" + PREAMBLE

TOC_START_MARKER = "<!-- TOC:START -->"
TOC_END_MARKER = "<!-- TOC:END -->"

CANDIDATE_CHANGES_START_MARKER = "<!-- BEGIN:AUTOGENERATED:CANDIDATE_CHANGES -->"
CANDIDATE_CHANGES_END_MARKER = "<!-- END:AUTOGENERATED:CANDIDATE_CHANGES -->"

RELEASE_TYPE_MAP = {
    "pre-release-alpha": "pre-release",
    "pre-release-rc": "release candidate",
    "public-release": "public release",
    "maintenance-release": "maintenance release",
}


class ChangelogGenerator:
    """
    Generates CHANGELOG sections for CAMARA API releases.

    Produces per-release-cycle files in a CHANGELOG/ directory using
    Mustache templates. Per-API documentation links are pre-formatted
    by Python and injected via triple-mustache.

    Example usage:
        generator = ChangelogGenerator()
        content = generator.generate_draft(
            release_tag="r4.1",
            metadata=metadata_dict,
            repo_name="QualityOnDemand",
            previous_release="r3.2",
            candidate_prs=[{"title": "Add feature", "author": "user", "url": "..."}],
        )
        path = generator.write_changelog("/tmp/repo", content, "r4.1", "QualityOnDemand")
    """

    DEFAULT_TEMPLATE_DIR = Path(__file__).parent.parent / "templates" / "changelog"

    def __init__(self, template_dir: Optional[str] = None):
        """Initialize with path to templates directory.

        Args:
            template_dir: Custom template directory path.
                         Defaults to release_automation/templates/changelog/
        """
        self.template_dir = Path(template_dir) if template_dir else self.DEFAULT_TEMPLATE_DIR
        self.renderer = pystache.Renderer(
            missing_tags='strict',
            escape=lambda x: x,  # Don't HTML-escape (markdown context)
        )

    def generate_draft(
        self,
        release_tag: str,
        metadata: Dict[str, Any],
        repo_name: str,
        candidate_changes: Optional[str] = None,
    ) -> str:
        """Generate CHANGELOG section content for a release.

        Args:
            release_tag: Target release tag (e.g., "r4.1")
            metadata: Generated release-metadata.yaml dict containing:
                - repository.release_type (e.g., "pre-release-alpha")
                - apis[].api_name, api_version, api_title, api_file_name
                - dependencies.commonalities_release, identity_consent_management_release
            repo_name: Repository name (e.g., "QualityOnDemand")
            candidate_changes: Pre-formatted markdown body from GitHub's
                generate-notes API (includes PR list and full changelog link).
                None if unavailable.

        Returns:
            Rendered template string (release section content)
        """
        # Extract API info for template
        apis = metadata.get("apis", [])
        api_list = [
            {"api_name": api.get("api_name", ""),
             "api_version": api.get("api_version", "")}
            for api in apis
        ]

        # Release type drives both the section heading description and the
        # generated per-API first sentence.
        release_type = metadata.get("repository", {}).get("release_type", "")

        # Pre-format API sections
        formatted_sections = []
        for api in apis:
            formatted_sections.append(
                self.format_api_section(
                    api, release_tag, repo_name, release_type=release_type
                )
            )
        formatted_api_sections = "\n\n".join(formatted_sections)

        # Get dependency versions
        deps = metadata.get("dependencies", {})
        commonalities = deps.get("commonalities_release", "")
        icm = deps.get("identity_consent_management_release", "")
        release_type_description = self._get_release_type_description(release_type)

        # Split candidate changes to extract Full Changelog link
        if candidate_changes:
            changes_body, full_changelog_url = self._split_candidate_changes(
                candidate_changes
            )
        else:
            changes_body = None
            full_changelog_url = None

        # Build template context
        context = {
            "release_tag": release_tag,
            "release_type_description": release_type_description,
            "apis": api_list,
            "commonalities_release": commonalities,
            "icm_release": icm,
            "formatted_api_sections": formatted_api_sections,
            "repo_name": repo_name,
            "candidate_changes": changes_body if changes_body else False,
            "full_changelog_url": full_changelog_url if full_changelog_url else False,
        }

        template_path = self.template_dir / "release_section.mustache"
        template_content = template_path.read_text()
        return self.renderer.render(template_content, context)

    def write_changelog(
        self,
        work_dir: str,
        content: str,
        release_tag: str,
        repo_name: str,
        release_type: str = "",
    ) -> str:
        """Write CHANGELOG section to the appropriate file.

        Target selection (maintenance releases preserve legacy flat CHANGELOG.md
        until the repo has been migrated to per-cycle via ``/migrate-changelog``):

            if release_type == "maintenance-release" and
               CHANGELOG/CHANGELOG-r{cycle}.md does NOT exist:
                write to CHANGELOG.md at the repo root (flat mode)
            else:
                write to CHANGELOG/CHANGELOG-r{cycle}.md (per-cycle mode)

        Behavior:
            - If file exists: prepend new section after the header block
            - If file is new: create with header + section

        Args:
            work_dir: Repository working directory
            content: Rendered release section content
            release_tag: Release tag for cycle extraction
            repo_name: Repository name for header generation
            release_type: Release type from release-plan/metadata; used only
                to enable flat-mode fallback for maintenance releases.

        Returns:
            Relative path to the written file, e.g. ``CHANGELOG/CHANGELOG-r4.md``
            (per-cycle) or ``CHANGELOG.md`` (flat).
        """
        cycle = self._get_cycle(release_tag)
        filepath, relative_path = self._resolve_changelog_path(
            Path(work_dir), cycle, release_type
        )

        if filepath.exists():
            existing = filepath.read_text()
            # Find end of header block (first "# r" heading after the preamble)
            # Insert new section after header, before existing release sections
            header_end = self._find_header_end(existing)
            new_content = existing[:header_end] + content + "\n" + existing[header_end:]
            filepath.write_text(new_content)
        else:
            header = self._generate_header(repo_name)
            filepath.write_text(header + "\n" + content + "\n")

        # Regenerate TOC after content changes
        self._update_toc(filepath)

        return relative_path

    @staticmethod
    def _resolve_changelog_path(
        work_dir: Path, cycle: str, release_type: str
    ) -> Tuple[Path, str]:
        """Pick flat vs per-cycle target for write_changelog().

        Flat mode (``CHANGELOG.md`` at repo root) activates only when the
        release is a maintenance release AND no per-cycle file exists yet
        for the target cycle. Every other case uses per-cycle, and the
        ``CHANGELOG/`` directory is created if missing.

        Returns:
            Tuple of (absolute Path to target file, relative path string).
        """
        per_cycle_file = work_dir / "CHANGELOG" / f"CHANGELOG-r{cycle}.md"
        if release_type == "maintenance-release" and not per_cycle_file.exists():
            return work_dir / "CHANGELOG.md", "CHANGELOG.md"

        per_cycle_file.parent.mkdir(exist_ok=True)
        return per_cycle_file, f"CHANGELOG/CHANGELOG-r{cycle}.md"

    def _find_header_end(self, content: str) -> int:
        """Find the position where release sections start in an existing file.

        The header block ends at the first level-1 heading that looks like
        a release tag (e.g., '# r3.2'). New sections are inserted before this.
        """
        lines = content.split("\n")
        pos = 0
        for line in lines:
            if re.match(r"^# r\d+\.", line):
                return pos
            pos += len(line) + 1  # +1 for newline
        # If no release heading found, append at end
        return len(content)

    def _get_cycle(self, release_tag: str) -> str:
        """Extract cycle number from release_tag.

        Args:
            release_tag: e.g., "r4.1", "r3.2", "r10.1"

        Returns:
            Cycle string, e.g., "4", "3", "10"
        """
        match = re.match(r"r(\d+)\.", release_tag)
        if not match:
            raise ValueError(f"Cannot extract cycle from release_tag: {release_tag}")
        return match.group(1)

    def _get_release_type_description(self, release_type: str) -> str:
        """Map release_type to human-readable description.

        Args:
            release_type: e.g., "alpha", "rc", "public"

        Returns:
            Human-readable description, e.g., "pre-release"
        """
        return RELEASE_TYPE_MAP.get(release_type, release_type)

    @staticmethod
    def _split_candidate_changes(raw: str) -> Tuple[str, Optional[str]]:
        """Split GitHub generate-notes output into PR list and Full Changelog URL.

        The GitHub API typically returns:
            ## What's Changed
            * PR title by @author in https://...
            ...
            **Full Changelog**: https://github.com/.../compare/TAG1...TAG2

        This method extracts the Full Changelog URL and returns the remaining
        body separately so the template can place them in different locations.

        Args:
            raw: Raw markdown body from GitHub's generate-notes API.

        Returns:
            Tuple of (pr_list_body, full_changelog_url).
            full_changelog_url is None if the link line is not found.
        """
        match = re.search(
            r"^\*\*Full Changelog\*\*:\s*(https?://\S+)\s*$",
            raw,
            re.MULTILINE,
        )
        if not match:
            return raw.rstrip(), None

        url = match.group(1)
        # Remove the Full Changelog line from the body
        body = raw[:match.start()] + raw[match.end():]
        return body.rstrip(), url

    def _generate_header(self, repo_name: str) -> str:
        """Generate the file header for new CHANGELOG files.

        Includes empty TOC markers between title and preamble.
        The TOC content is populated by _update_toc() after sections
        are written.

        Args:
            repo_name: Repository name (e.g., "QualityOnDemand")

        Returns:
            Header text including title, TOC markers, and recording rules.
        """
        title = TITLE_TEMPLATE.format(repo_name=repo_name)
        return f"{title}\n\n{TOC_START_MARKER}\n{TOC_END_MARKER}\n\n{PREAMBLE}"

    @staticmethod
    def _heading_to_anchor(heading_text: str) -> str:
        """Convert heading text to a GitHub-compatible anchor ID.

        GitHub anchor rules: lowercase, remove dots/special chars
        (except hyphens), replace spaces with hyphens.

        Examples:
            "r3.2"         -> "r32"
            "r10.1"        -> "r101"
            "v0.10.0-rc2"  -> "v0100-rc2"
        """
        text = heading_text.lower()
        text = text.replace(".", "")
        text = text.replace(" ", "-")
        text = re.sub(r"[^a-z0-9\-]", "", text)
        return text

    @staticmethod
    def _extract_toc_entries(content: str) -> List[Dict[str, Any]]:
        """Extract TOC entries from file content by scanning level-1 headings.

        Finds all ``# rX.Y`` release-tag headings (optionally followed by
        trailing descriptor text, e.g. ``# r2.2 - Fall25 public release``)
        and determines if the release is a public release (bold in TOC)
        by checking the "This {type} contains" line in the few lines
        following the heading.

        ``heading`` is the full heading text after ``# `` — used both as
        the TOC link label and as the anchor source so link text and
        anchor track what the underlying heading actually says.

        Returns:
            List of dicts ordered by appearance (newest first):
            ``[{"heading": "r4.2", "is_public": True}, ...]``
        """
        lines = content.split("\n")
        entries: List[Dict[str, Any]] = []
        for i, line in enumerate(lines):
            if not re.match(r"^#\s+r\d+\.\d+\b", line):
                continue
            heading = line.lstrip("#").strip()
            is_public = False
            for j in range(i + 1, min(i + 6, len(lines))):
                if re.search(
                    r"This (public release|maintenance release) contains",
                    lines[j],
                ):
                    is_public = True
                    break
            entries.append({"heading": heading, "is_public": is_public})
        return entries

    @staticmethod
    def _format_toc(entries: List[Dict[str, Any]]) -> str:
        """Format TOC entries into markdown.

        Public/maintenance releases are bold, pre-releases are plain.
        Link text and anchor both derive from the full heading text so
        the TOC faithfully mirrors each heading and the anchor matches
        GitHub's rendered anchor for that heading.

        Returns:
            TOC section string including ``## Table of Contents`` heading,
            or empty string if no entries.
        """
        if not entries:
            return ""
        lines = ["## Table of Contents"]
        for entry in entries:
            heading = entry["heading"]
            anchor = ChangelogGenerator._heading_to_anchor(heading)
            link = f"[{heading}](#{anchor})"
            if entry["is_public"]:
                lines.append(f"- **{link}**")
            else:
                lines.append(f"- {link}")
        return "\n".join(lines) + "\n"

    def _update_toc(self, filepath: Path) -> None:
        """Regenerate the TOC in-place for the given CHANGELOG file.

        If TOC markers exist, replaces content between them.
        If no markers found (legacy file), inserts TOC after the title line.
        """
        content = filepath.read_text()
        entries = self._extract_toc_entries(content)
        toc_text = self._format_toc(entries)

        start_idx = content.find(TOC_START_MARKER)
        end_idx = content.find(TOC_END_MARKER)

        if start_idx != -1 and end_idx != -1:
            # Replace between markers
            end_of_end_marker = end_idx + len(TOC_END_MARKER)
            if end_of_end_marker < len(content) and content[end_of_end_marker] == "\n":
                end_of_end_marker += 1
            new_content = (
                content[:start_idx]
                + TOC_START_MARKER + "\n"
                + toc_text
                + TOC_END_MARKER + "\n"
                + content[end_of_end_marker:]
            )
        else:
            # Fallback: insert after title line
            first_newline = content.index("\n")
            new_content = (
                content[:first_newline + 1]
                + "\n" + TOC_START_MARKER + "\n"
                + toc_text
                + TOC_END_MARKER + "\n"
                + content[first_newline + 1:]
            )

        filepath.write_text(new_content)

    @staticmethod
    def _parse_version(version: str) -> Tuple[Optional[Tuple[int, int, int]], Optional[int]]:
        """Parse a CAMARA version string into numeric parts.

        Accepts the ``v``-prefixed form used in CHANGELOG headings, e.g.
        ``v1.1.0`` or ``v0.1.0-alpha.1``.

        Returns:
            Tuple of ((major, minor, patch), pre_release_number). Either
            element is None when it cannot be determined: the numeric triple
            is None for unparseable versions (e.g. ``wip``); the pre-release
            number is None when there is no ``-alpha.N`` / ``-rc.N`` suffix.
        """
        core = version[1:] if version[:1] in ("v", "V") else version
        base, _, suffix = core.partition("-")
        parts = base.split(".")
        if len(parts) != 3:
            return None, None
        try:
            major, minor, patch = (int(p) for p in parts)
        except ValueError:
            return None, None
        pre_num = None
        if suffix:
            match = re.search(r"(\d+)", suffix)
            if match:
                pre_num = int(match.group(1))
        return (major, minor, patch), pre_num

    @classmethod
    def _version_descriptor(cls, version: str, release_type: str) -> Optional[str]:
        """Describe a release in one phrase, from its version and type.

        Returns a descriptor that slots into
        ``{api} {version} is {descriptor} of this API.`` Ordinality ("first")
        is claimed only where the version alone proves it
        (``v0.1.0-alpha.1``, ``v0.1.0-rc.1``, ``v1.0.0``). Returns None when
        no descriptor applies (unknown release type or unparseable version),
        so the caller keeps the ``...`` placeholder.

        Descriptor table agreed on ReleaseManagement#552.
        """
        nums, pre_num = cls._parse_version(version)
        if nums is None:
            return None
        major, minor, patch = nums
        is_first_010 = nums == (0, 1, 0) and pre_num == 1

        if release_type == "pre-release-alpha":
            return "the first alpha version" if is_first_010 else "an alpha version"
        if release_type == "pre-release-rc":
            return (
                "the first release-candidate version"
                if is_first_010
                else "a release-candidate version"
            )
        if release_type == "maintenance-release":
            return "a patch update"
        if release_type == "public-release":
            if major == 0:
                return "an initial public version"
            if nums == (1, 0, 0):
                return "the first stable version"
            if major >= 2 and minor == 0 and patch == 0:
                return "a new major version"
            if patch >= 1:
                return "a patch update"
            if minor >= 1:
                return "a minor update"
        return None

    @classmethod
    def format_api_section(
        cls,
        api: Dict[str, str],
        release_tag: str,
        repo_name: str,
        org: str = "camaraproject",
        release_type: str = "",
    ) -> str:
        """Format a single API's CHANGELOG section with links.

        Pre-generates the complex multi-line structure including heading,
        description, documentation links, and change category stubs.

        Args:
            api: Dict with api_name, api_version, api_file_name
            release_tag: For URL construction
            repo_name: For URL construction
            org: GitHub organization
            release_type: Release type from metadata (e.g.
                "pre-release-alpha"); drives the generated first sentence.
                When empty or unrecognised, the ``...`` placeholder is kept.

        Returns:
            Formatted markdown section for this API
        """
        title = api.get("api_name", "")
        version = api.get("api_version", "")
        file_name = api.get("api_file_name", api.get("api_name", ""))
        yaml_path = f"code/API_definitions/{file_name}.yaml"

        base_url = f"https://github.com/{org}/{repo_name}"
        raw_url = f"https://raw.githubusercontent.com/{org}/{repo_name}"

        descriptor = cls._version_descriptor(version, release_type)
        if descriptor:
            first_sentence = f"**{title} {version} is {descriptor} of this API.**"
        else:
            first_sentence = f"**{title} {version} is ...**"

        comparison_baseline = api.get("comparison_baseline", "")
        lines = [
            f"## {title} {version}",
            "",
            first_sentence,
            "",
        ]
        if comparison_baseline:
            lines.extend([
                f"Changes documented below are compared to version {comparison_baseline}.",
                "",
            ])
        lines.extend([
            "- API definition **with inline documentation**:",
            f"  - [View it on ReDoc](https://redocly.github.io/redoc/"
            f"?url={raw_url}/{release_tag}/{yaml_path}&nocors)",
            f"  - [View it on Swagger Editor](https://camaraproject.github.io/swagger-ui/"
            f"?url={raw_url}/{release_tag}/{yaml_path})",
            f"  - OpenAPI [YAML spec file]({base_url}/blob/{release_tag}/{yaml_path})",
            "",
            "### Breaking changes",
            "",
            "* N/A",
            "",
            "### Added",
            "",
            "* N/A",
            "",
            "### Changed",
            "",
            "* N/A",
            "",
            "### Fixed",
            "",
            "* N/A",
            "",
            "### Removed",
            "",
            "* N/A",
        ])

        return "\n".join(lines)
